{
	"version": 1763915827,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/ror-sheet0.png",
		"images/camera-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/samurai-sheet0.png",
		"images/samurai-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/musuh-sheet0.png",
		"images/musuh-sheet1.png",
		"images/balik-sheet0.png",
		"images/hitbox_samurai-sheet0.png",
		"images/darah_enemy-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite14-sheet0.png",
		"images/darah_samurai-sheet0.png",
		"images/hitbox_musuh-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/wadahbar-sheet0.png",
		"images/barhijau-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/bg-sheet0.png",
		"images/mountain-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/spritefont.png",
		"images/spritefont2.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/tombolattack-sheet0.png",
		"images/kiri-sheet0.png",
		"images/kanan-sheet0.png",
		"images/atas-sheet0.png",
		"media/sword slash1_cut (mp3cut.net).m4a",
		"media/sword slash1_cut (mp3cut.net).ogg",
		"media/sword slash (sound effects) mani creation (mp3cut.net).m4a",
		"media/sword slash (sound effects) mani creation (mp3cut.net).ogg",
		"media/jim yosef - samurai drumstep ncs - copyright free music (mp3cut.net).m4a",
		"media/jim yosef - samurai drumstep ncs - copyright free music (mp3cut.net).ogg",
		"media/fighting action no copyright music(action background music) - drums percussion [no copyright-free] (mp3cut.net).m4a",
		"media/fighting action no copyright music(action background music) - drums percussion [no copyright-free] (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}